/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as DetectionsRouteImport } from './routes/detections'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'

const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsRoute = DetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/detections': typeof DetectionsRoute
  '/intel': typeof IntelRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/detections': typeof DetectionsRoute
  '/intel': typeof IntelRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/detections': typeof DetectionsRoute
  '/intel': typeof IntelRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/cases'
    | '/detections'
    | '/intel'
    | '/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/cases' | '/detections' | '/intel' | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/cases'
    | '/detections'
    | '/intel'
    | '/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CasesRoute: typeof CasesRouteWithChildren
  DetectionsRoute: typeof DetectionsRoute
  IntelRoute: typeof IntelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections': {
      id: '/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof DetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CasesRoute: CasesRouteWithChildren,
  DetectionsRoute: DetectionsRoute,
  IntelRoute: IntelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
