/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as SpoofingRouteImport } from './routes/spoofing'
import { Route as ScreenshotsRouteImport } from './routes/screenshots'
import { Route as RegulationsRouteImport } from './routes/regulations'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as DetectionsRouteImport } from './routes/detections'
import { Route as CoordinationRouteImport } from './routes/coordination'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as CasesCaseIdBriefRouteImport } from './routes/cases.$caseId.brief'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofingRoute = SpoofingRouteImport.update({
  id: '/spoofing',
  path: '/spoofing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotsRoute = ScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationsRoute = RegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsRoute = DetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinationRoute = CoordinationRouteImport.update({
  id: '/coordination',
  path: '/coordination',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdBriefRoute = CasesCaseIdBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => CasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/coordination': typeof CoordinationRoute
  '/detections': typeof DetectionsRoute
  '/doctrine': typeof DoctrineRoute
  '/intel': typeof IntelRoute
  '/operators': typeof OperatorsRoute
  '/regulations': typeof RegulationsRoute
  '/screenshots': typeof ScreenshotsRoute
  '/spoofing': typeof SpoofingRoute
  '/violations': typeof ViolationsRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/brief': typeof CasesCaseIdBriefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/coordination': typeof CoordinationRoute
  '/detections': typeof DetectionsRoute
  '/doctrine': typeof DoctrineRoute
  '/intel': typeof IntelRoute
  '/operators': typeof OperatorsRoute
  '/regulations': typeof RegulationsRoute
  '/screenshots': typeof ScreenshotsRoute
  '/spoofing': typeof SpoofingRoute
  '/violations': typeof ViolationsRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/brief': typeof CasesCaseIdBriefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/coordination': typeof CoordinationRoute
  '/detections': typeof DetectionsRoute
  '/doctrine': typeof DoctrineRoute
  '/intel': typeof IntelRoute
  '/operators': typeof OperatorsRoute
  '/regulations': typeof RegulationsRoute
  '/screenshots': typeof ScreenshotsRoute
  '/spoofing': typeof SpoofingRoute
  '/violations': typeof ViolationsRoute
  '/cases/$caseId': typeof CasesCaseIdRouteWithChildren
  '/cases/$caseId/brief': typeof CasesCaseIdBriefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/cases'
    | '/coordination'
    | '/detections'
    | '/doctrine'
    | '/intel'
    | '/operators'
    | '/regulations'
    | '/screenshots'
    | '/spoofing'
    | '/violations'
    | '/cases/$caseId'
    | '/cases/$caseId/brief'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/cases'
    | '/coordination'
    | '/detections'
    | '/doctrine'
    | '/intel'
    | '/operators'
    | '/regulations'
    | '/screenshots'
    | '/spoofing'
    | '/violations'
    | '/cases/$caseId'
    | '/cases/$caseId/brief'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/cases'
    | '/coordination'
    | '/detections'
    | '/doctrine'
    | '/intel'
    | '/operators'
    | '/regulations'
    | '/screenshots'
    | '/spoofing'
    | '/violations'
    | '/cases/$caseId'
    | '/cases/$caseId/brief'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CasesRoute: typeof CasesRouteWithChildren
  CoordinationRoute: typeof CoordinationRoute
  DetectionsRoute: typeof DetectionsRoute
  DoctrineRoute: typeof DoctrineRoute
  IntelRoute: typeof IntelRoute
  OperatorsRoute: typeof OperatorsRoute
  RegulationsRoute: typeof RegulationsRoute
  ScreenshotsRoute: typeof ScreenshotsRoute
  SpoofingRoute: typeof SpoofingRoute
  ViolationsRoute: typeof ViolationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoofing': {
      id: '/spoofing'
      path: '/spoofing'
      fullPath: '/spoofing'
      preLoaderRoute: typeof SpoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshots': {
      id: '/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof ScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulations': {
      id: '/regulations'
      path: '/regulations'
      fullPath: '/regulations'
      preLoaderRoute: typeof RegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections': {
      id: '/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof DetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordination': {
      id: '/coordination'
      path: '/coordination'
      fullPath: '/coordination'
      preLoaderRoute: typeof CoordinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId/brief': {
      id: '/cases/$caseId/brief'
      path: '/brief'
      fullPath: '/cases/$caseId/brief'
      preLoaderRoute: typeof CasesCaseIdBriefRouteImport
      parentRoute: typeof CasesCaseIdRoute
    }
  }
}

interface CasesCaseIdRouteChildren {
  CasesCaseIdBriefRoute: typeof CasesCaseIdBriefRoute
}

const CasesCaseIdRouteChildren: CasesCaseIdRouteChildren = {
  CasesCaseIdBriefRoute: CasesCaseIdBriefRoute,
}

const CasesCaseIdRouteWithChildren = CasesCaseIdRoute._addFileChildren(
  CasesCaseIdRouteChildren,
)

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRouteWithChildren
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRouteWithChildren,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CasesRoute: CasesRouteWithChildren,
  CoordinationRoute: CoordinationRoute,
  DetectionsRoute: DetectionsRoute,
  DoctrineRoute: DoctrineRoute,
  IntelRoute: IntelRoute,
  OperatorsRoute: OperatorsRoute,
  RegulationsRoute: RegulationsRoute,
  ScreenshotsRoute: ScreenshotsRoute,
  SpoofingRoute: SpoofingRoute,
  ViolationsRoute: ViolationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
